### ISSUE TITLE
ms_api_copy.py file doesn't existing in the repo 

### ISSUE THREAD

**Issue by asciiwalker** [EZ-hwh/AutoCrawler#3]
ModuleNotFoundError: No module named 'utils.ms_api_copy'

**Comment by NozoMizore7** [comment]
same issue met

**Comment by abhaylb** [comment]
hey @EZ-hwh , Can you help here? I saw this file is excluded in .gitignore but this file import is there at a few places which is causing errors in running the mentioned command in READMe file.

**Comment by abhaylb** [comment]
hey @EZ-hwh , Can you help test the repository code? I have been able to set up the repo with requirements.txt installation successfully. Just need ms_api_copy.py file for running those command mentioned in README.md file

**Comment by EZ-hwh** [comment]
> hey @EZ-hwh , Can you help test the repository code? I have been able to set up the repo with requirements.txt installation successfully. Just need ms_api_copy.py file for running those command mentioned in README.md file

ms_api_copy.py is just a file that just contains simple OpenAI API execution code. You can reimplement it refering to utils/api.py.

**Comment by 11PRiyansh** [comment]
@asciiwalker Were you able to re-implement it?

**Comment by JanusChoi** [comment]
Should be just like:
```
import openai

# Replace 'your-api-key' with your actual OpenAI API key
OPENAI_API_KEY = 'your-api-key'

openai.api_key = OPENAI_API_KEY

def ms_chatgpt(query):
    response = openai.ChatCompletion.create(
        model="gpt-3.5-turbo",  # or another model like "gpt-4"
        messages=[
            {"role": "system", "content": "You are a helpful assistant."},
            {"role": "user", "content": query},
        ],
        max_tokens=150,
        n=1,
        stop=None,
        temperature=0.7,
    )
    return response['choices'][0]['message']['content']

# Example usage
if __name__ == "__main__":
    print(ms_chatgpt("How do I calculate the 100th prime number in Python?"))
```
